### ISSUE TITLE
Potential of coroner causing lag

### ISSUE THREAD

**Issue by Bryantdl7** [Darkstorm-Servers/Bugs#6]
Please investigate if the way coroner networks its kills and deaths to users causes lag, research in the past indicated so.

This is fairly old code dating back to the mechanist days so I will set this one as high priority.

**Comment by hounddogie** [comment]
Investigation complete. The code wouldn't be the cause of server lag or ping drop from what I see.

See the updated code [here](https://git.darkstorm.cc/dstm/build-addons/src/branch/main/coroner-persistent-kd/lua/autorun/server/coroner.lua)

For the full evaluation on the code.

**Comment by hounddogie** [comment]
According to my evaluation of the code, Coroner is not causing lag.
